build website:
  stage: build
  image: node:14
  script:
    - npm install
    - npm build
  artifacts:
    paths:
      - public  

run tests:
  stage: test
  image: node:14
  script:
    - npm test

deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 cp public s3://$S3_BUCKET --recursive